name: Build and Release Godot Game

on:
  push:
    branches:
      - main

jobs:
  export_game:
    # Only runs if the commit message starts with "build"
    if: startsWith(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Ensures all history is available

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.6.1&flavor=stable&slug=win64.exe.zip&platform=windows.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.6.1&flavor=stable&slug=export_templates.tpz&platform=templates
          relative_project_path: ./
          archive_output: true

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: build-${{ github.sha }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          allowUpdates: true
          
